### ISSUE TITLE
how to ignore ssl check?

### ISSUE THREAD

**Issue by terryzwt** [k8s-client/client#1]
While using self-signed cert, got below error.
I think disable the ssl check on may fixed it, but I don't know how to do it.
May you please provide a sample for it? thanks.

Here is the code:
```
use K8s\Api\Model\Api\Core\v1\Pod;
use K8s\Client\K8sFactory;

$k8s = (new K8sFactory())->loadFromKubeConfig();

/** @var Pod $pod */
foreach ($k8s->listAll(Pod::class) as $pod) {
  echo sprintf(
      "%s\t%s\t%s",
      $pod->getPodIP(),
      $pod->getNamespace(),
      $pod->getName()
    ) . PHP_EOL;
}
```

```
PHP Fatal error:  Uncaught Symfony\Component\HttpClient\Exception\TransportException: SSL peer certificate or SSH remote key was not OK for "https://192.168.68.10:6443/api/v1/pods". in /Users/terry/www/php-k8s-client/vendor/symfony/http-client/Response/CurlResponse.php:317
Stack trace:
#0 /Users/terry/www/php-k8s-client/vendor/symfony/http-client/Response/TransportResponseTrait.php(170): Symfony\Component\HttpClient\Response\CurlResponse::perform(Object(Symfony\Component\HttpClient\Internal\CurlClientState), Array)
#1 /Users/terry/www/php-k8s-client/vendor/symfony/http-client/Response/CommonResponseTrait.php(156): Symfony\Component\HttpClient\Response\CurlResponse::stream(Array)
#2 /Users/terry/www/php-k8s-client/vendor/symfony/http-client/Response/TransportResponseTrait.php(53): Symfony\Component\HttpClient\Response\CurlResponse::initialize(Object(Symfony\Component\HttpClient\Response\CurlResponse))
#3 /Users/terry/www/php-k8s-client/vendor/symfony/http-client/Psr18Client.php(99): Symfony\Component\HttpClient\Response\CurlRes in /Users/terry/www/php-k8s-client/vendor/symfony/http-client/Psr18Client.php on line 120

```

**Comment by ChadSikorra** [comment]
I think you would need to do something like this:

```php
use K8s\HttpSymfony\ClientFactory;
use K8s\Client\K8sFactory;

$httpFactory = new ClientFactory([
    'verify_peer' => false,
    'verify_host' => false,
]);

$k8s = (new K8sFactory())->loadFromKubeConfig(null, $httpFactory);
```

I added this to the docs for the Symfony HTTP client part here:

https://github.com/k8s-client/http-symfony#default-http-options-configuration

Let me know if this helps!

**Comment by terryzwt** [comment]
@ChadSikorra Thanks.
got below error.
1. $k8s is init sucessfully
2. `kubectl get po -A` can execute sucessfully
```
PHP Fatal error:  Uncaught K8s\Client\Exception\KubernetesException: pods is forbidden: User "system:anonymous" cannot list resource "pods" in API group "" at the cluster scope in /Users/terry/www/php-k8s-client/vendor/k8s/client/src/K8s/Client/Http/ResponseHandler/ErrorHandler.php:36
Stack trace:
#0 /Users/terry/www/php-k8s-client/vendor/k8s/client/src/K8s/Client/Http/HttpClient.php(109): K8s\Client\Http\ResponseHandler\ErrorHandler->handle(Object(Nyholm\Psr7\Response), Array)
#1 /Users/terry/www/php-k8s-client/vendor/k8s/client/src/K8s/Client/Kind/KindManager.php(397): K8s\Client\Http\HttpClient->send('https://192.168...', 'list', Array)
#2 /Users/terry/www/php-k8s-client/vendor/k8s/client/src/K8s/Client/Kind/KindManager.php(273): K8s\Client\Kind\KindManager->execute('list-all', Array, 'K8s\\Api\\Model\\A...')
#3 /Users/terry/www/php-k8s-client/vendor/k8s/client/src/K8s/Client/K8s.php(199): K8s\Client\Kind\KindManager->listAll('K8s\\Api\\Model\\A...', Array)
#4 /Users/terry/www/php-k8s-client/demo.php(46): K8s\Client\K8s->li in /Users/terry/www/php-k8s-client/vendor/k8s/client/src/K8s/Client/Http/ResponseHandler/ErrorHandler.php on line 36

```

**Comment by ChadSikorra** [comment]
What does your kubeconfig file look like? (just remove anything sensitive..). My guess is maybe it uses exec or something else this library doesn't support yet.

**Comment by terryzwt** [comment]
I send it to Chad.Sikorra@gmail.com( find it from https://www.chadsikorra.com/about)

**Comment by ChadSikorra** [comment]
Thanks, got it. After looking at it, it appears that for authentication it uses client certificates as base64 strings. The issue is that there is no way in PHP (for cURL anyway) to specify a certificate from anything other than a file path. So a workaround would have to include writing the certificate data locally on the filesystem somewhere, then referencing it for the options in Symfony.

I'll have to think a bit on how I want to do this.

An alternative workaround for the moment could be to reference a file path to the certificate using `client-certificate` and `client-key` in your kubeconfig.

**Comment by terryzwt** [comment]
@ChadSikorra 
After using the certs file, it works. Thanks for help!

**Comment by ChadSikorra** [comment]
PHP 8.1+ and newer libcurl versions added support for using string cert data instead of file paths. I added support for this in the the Symfony HTTP Client adapter (Guzzle does not support adding these options unfortunately). Tagged a new release for it:

https://github.com/k8s-client/http-symfony/releases/tag/1.1.0
